<?php

namespace Database\Seeders;

use App\Models\Crop;
use Illuminate\Database\Seeder;

class CropSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $crops = [
            // Other Vegetables (category_id = 13)
            [
                'category_id' => 13,
                'name' => 'Ampalaya',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 20000,
                'maturity' => '60-75 DAP',
                'volume_of_production' => '8-15',
                'distance_of_planting_hills' => 100,
                'distance_of_planting_rows' => 150,
                'yield_per_hectare' => '8-15 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Upo',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'October March',
                'plant_population_per_hectare' => 3333,
                'maturity' => '90-100 DAP',
                'volume_of_production' => '5-10',
                'distance_of_planting_hills' => 100,
                'distance_of_planting_rows' => 300,
                'yield_per_hectare' => '5-10 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Broccoli',
                'crop_season' => 'dry',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'October December',
                'plant_population_per_hectare' => 50000,
                'maturity' => '50-65 DAP',
                'volume_of_production' => '4-10',
                'distance_of_planting_hills' => 40,
                'distance_of_planting_rows' => 50,
                'yield_per_hectare' => '4-10 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Onion',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'October February',
                'plant_population_per_hectare' => 444444,
                'maturity' => '3-4 Months After Transplant',
                'volume_of_production' => '8-15',
                'distance_of_planting_hills' => 15,
                'distance_of_planting_rows' => 15,
                'yield_per_hectare' => '8-15 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Bush Sitao',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'November - March',
                'plant_population_per_hectare' => 133333,
                'maturity' => '45-50 DAP',
                'volume_of_production' => '8-10',
                'distance_of_planting_hills' => 10,
                'distance_of_planting_rows' => 75,
                'yield_per_hectare' => '8-10 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Bush Snap Bean',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'October January',
                'plant_population_per_hectare' => 33333,
                'maturity' => '50 DAP',
                'volume_of_production' => '8-12',
                'distance_of_planting_hills' => 40,
                'distance_of_planting_rows' => 75,
                'yield_per_hectare' => '8-12 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Cabbage',
                'crop_season' => 'dry',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'October December',
                'plant_population_per_hectare' => 41666,
                'maturity' => '55-60 DAP',
                'volume_of_production' => '20-25',
                'distance_of_planting_hills' => 40,
                'distance_of_planting_rows' => 60,
                'yield_per_hectare' => '20-25 tons',
            ],
            [
                'category_id' => 11,
                'name' => 'Cantaloupe',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained sandy loam',
                'time_of_planting' => 'September February',
                'plant_population_per_hectare' => 20000,
                'maturity' => '85-90 Days After Transplant',
                'volume_of_production' => '5-30',
                'distance_of_planting_hills' => 50,
                'distance_of_planting_rows' => 100,
                'yield_per_hectare' => '5-30 tons',
            ],
            [
                'category_id' => 9,
                'name' => 'Carrot',
                'crop_season' => 'all',
                'soil_type' => 'sandy loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 333333,
                'maturity' => '75-103 Days After Sowing',
                'volume_of_production' => '4-8',
                'distance_of_planting_hills' => 15,
                'distance_of_planting_rows' => 20,
                'yield_per_hectare' => '4-8 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Cauliflower',
                'crop_season' => 'dry',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'September January',
                'plant_population_per_hectare' => 47619,
                'maturity' => '45-60 DAT',
                'volume_of_production' => '20,000 heads',
                'distance_of_planting_hills' => 35,
                'distance_of_planting_rows' => 60,
                'yield_per_hectare' => '20,000 heads',
            ],
            [
                'category_id' => 13,
                'name' => 'Celery',
                'crop_season' => 'dry',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'September January',
                'plant_population_per_hectare' => 250000,
                'maturity' => '65-75 DAP',
                'volume_of_production' => '5-6',
                'distance_of_planting_hills' => 20,
                'distance_of_planting_rows' => 20,
                'yield_per_hectare' => '5-6 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Chayote',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'September January',
                'plant_population_per_hectare' => 12500,
                'maturity' => '6-10 DAT',
                'volume_of_production' => '2.5-4.0',
                'distance_of_planting_hills' => 40,
                'distance_of_planting_rows' => 200,
                'yield_per_hectare' => '2.5-4.0 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Chick Pea',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'September January',
                'plant_population_per_hectare' => 133333,
                'maturity' => '60-90 DAT',
                'volume_of_production' => '2.5-3.0',
                'distance_of_planting_hills' => 15,
                'distance_of_planting_rows' => 50,
                'yield_per_hectare' => '2.5-3.0 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Chinese Cabbage',
                'crop_season' => 'dry',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'October December',
                'plant_population_per_hectare' => 166667,
                'maturity' => '55-65 Days After Transplant',
                'volume_of_production' => '10-25',
                'distance_of_planting_hills' => 20,
                'distance_of_planting_rows' => 30,
                'yield_per_hectare' => '10-25 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Cowpea',
                'crop_season' => 'all',
                'soil_type' => 'sandy loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 200000,
                'maturity' => '60-75 Days After Planting',
                'volume_of_production' => '8-10 tons (green pods)',
                'distance_of_planting_hills' => 10,
                'distance_of_planting_rows' => 50,
                'yield_per_hectare' => '8-10 tons (green pods)',
            ],
            [
                'category_id' => 10,
                'name' => 'Cucumber',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'May - July Oct. Dec.',
                'plant_population_per_hectare' => 44444,
                'maturity' => '50-65 DAP',
                'volume_of_production' => '10-15',
                'distance_of_planting_hills' => 50,
                'distance_of_planting_rows' => 100,
                'yield_per_hectare' => '10-15 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Eggplant',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 33333,
                'maturity' => '90-120 DAP',
                'volume_of_production' => '9-11',
                'distance_of_planting_hills' => 75,
                'distance_of_planting_rows' => 100,
                'yield_per_hectare' => '9-11 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Hyacinth Beans (Bataw)',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 12500,
                'maturity' => '75-90 DAP',
                'volume_of_production' => '10,000-15,000 pods',
                'distance_of_planting_hills' => 80,
                'distance_of_planting_rows' => 100,
                'yield_per_hectare' => '10,000-15,000 pods',
            ],
            [
                'category_id' => 13,
                'name' => 'Kangkong (Water Spinach)',
                'crop_season' => 'all',
                'soil_type' => 'fertile, moist soil',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 500000,
                'maturity' => '20-30 DAP',
                'volume_of_production' => '10-15',
                'distance_of_planting_hills' => 10,
                'distance_of_planting_rows' => 20,
                'yield_per_hectare' => '10-15 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Lettuce',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'October - February',
                'plant_population_per_hectare' => 83333,
                'maturity' => '40-60 DAP',
                'volume_of_production' => '8-12',
                'distance_of_planting_hills' => 20,
                'distance_of_planting_rows' => 60,
                'yield_per_hectare' => '8-12 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Mustard',
                'crop_season' => 'all',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 333333,
                'maturity' => '25-40 DAP',
                'volume_of_production' => '5-8',
                'distance_of_planting_hills' => 15,
                'distance_of_planting_rows' => 20,
                'yield_per_hectare' => '5-8 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Okra',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 44444,
                'maturity' => '50-60 DAP',
                'volume_of_production' => '8-12',
                'distance_of_planting_hills' => 50,
                'distance_of_planting_rows' => 100,
                'yield_per_hectare' => '8-12 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Pechay',
                'crop_season' => 'all',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 200000,
                'maturity' => '20-30 DAP',
                'volume_of_production' => '6-10',
                'distance_of_planting_hills' => 15,
                'distance_of_planting_rows' => 33,
                'yield_per_hectare' => '6-10 tons',
            ],
            [
                'category_id' => 9,
                'name' => 'Radish',
                'crop_season' => 'dry',
                'soil_type' => 'sandy loam',
                'time_of_planting' => 'October - February',
                'plant_population_per_hectare' => 333333,
                'maturity' => '30-40 DAP',
                'volume_of_production' => '8-15',
                'distance_of_planting_hills' => 10,
                'distance_of_planting_rows' => 30,
                'yield_per_hectare' => '8-15 tons',
            ],
            [
                'category_id' => 13,
                'name' => 'Spinach',
                'crop_season' => 'dry',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'October - February',
                'plant_population_per_hectare' => 400000,
                'maturity' => '30-45 DAP',
                'volume_of_production' => '5-8',
                'distance_of_planting_hills' => 10,
                'distance_of_planting_rows' => 25,
                'yield_per_hectare' => '5-8 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Sweet Pepper',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 26667,
                'maturity' => '75-90 DAP',
                'volume_of_production' => '15-25',
                'distance_of_planting_hills' => 50,
                'distance_of_planting_rows' => 150,
                'yield_per_hectare' => '15-25 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Tomato',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 40000,
                'maturity' => '75-95 DAP',
                'volume_of_production' => '20-40',
                'distance_of_planting_hills' => 50,
                'distance_of_planting_rows' => 125,
                'yield_per_hectare' => '20-40 tons',
            ],
            [
                'category_id' => 10,
                'name' => 'Winter Melon',
                'crop_season' => 'dry',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'October - March',
                'plant_population_per_hectare' => 5000,
                'maturity' => '120-150 DAP',
                'volume_of_production' => '15-25',
                'distance_of_planting_hills' => 200,
                'distance_of_planting_rows' => 200,
                'yield_per_hectare' => '15-25 tons',
            ],
            // Rice (category_id = 8)
            [
                'category_id' => 8,
                'name' => 'Rice (Lowland)',
                'crop_season' => 'wet',
                'soil_type' => 'clay loam',
                'time_of_planting' => 'June - September',
                'plant_population_per_hectare' => 2500000,
                'maturity' => '120-150 DAP',
                'volume_of_production' => '3-6',
                'distance_of_planting_hills' => 20,
                'distance_of_planting_rows' => 20,
                'yield_per_hectare' => '3-6 tons',
            ],
            // Corn (category_id = 1)
            [
                'category_id' => 1,
                'name' => 'Corn (Yellow)',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 62500,
                'maturity' => '90-120 DAP',
                'volume_of_production' => '4-8',
                'distance_of_planting_hills' => 25,
                'distance_of_planting_rows' => 75,
                'yield_per_hectare' => '4-8 tons',
            ],
            [
                'category_id' => 1,
                'name' => 'Sweet Corn',
                'crop_season' => 'all',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 66667,
                'maturity' => '75-90 DAP',
                'volume_of_production' => '8-15',
                'distance_of_planting_hills' => 25,
                'distance_of_planting_rows' => 60,
                'yield_per_hectare' => '8-15 tons',
            ],
            // Root Crops (category_id = 9)
            [
                'category_id' => 9,
                'name' => 'Sweet Potato',
                'crop_season' => 'all',
                'soil_type' => 'sandy loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 44444,
                'maturity' => '90-120 DAP',
                'volume_of_production' => '10-20',
                'distance_of_planting_hills' => 30,
                'distance_of_planting_rows' => 75,
                'yield_per_hectare' => '10-20 tons',
            ],
            [
                'category_id' => 9,
                'name' => 'Cassava',
                'crop_season' => 'all',
                'soil_type' => 'well-drained sandy loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 12500,
                'maturity' => '8-12 months',
                'volume_of_production' => '15-25',
                'distance_of_planting_hills' => 100,
                'distance_of_planting_rows' => 80,
                'yield_per_hectare' => '15-25 tons',
            ],
            [
                'category_id' => 9,
                'name' => 'Potato',
                'crop_season' => 'dry',
                'soil_type' => 'sandy loam',
                'time_of_planting' => 'October - February',
                'plant_population_per_hectare' => 55556,
                'maturity' => '90-120 DAP',
                'volume_of_production' => '15-25',
                'distance_of_planting_hills' => 30,
                'distance_of_planting_rows' => 60,
                'yield_per_hectare' => '15-25 tons',
            ],
            // Fruits (category_id = 11)
            [
                'category_id' => 11,
                'name' => 'Watermelon',
                'crop_season' => 'dry',
                'soil_type' => 'sandy loam',
                'time_of_planting' => 'October - March',
                'plant_population_per_hectare' => 3333,
                'maturity' => '80-100 DAP',
                'volume_of_production' => '20-40',
                'distance_of_planting_hills' => 200,
                'distance_of_planting_rows' => 150,
                'yield_per_hectare' => '20-40 tons',
            ],
            // Fruit Trees (category_id = 2)
            [
                'category_id' => 2,
                'name' => 'Papaya',
                'crop_season' => 'all',
                'soil_type' => 'well-drained loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 1600,
                'maturity' => '10-12 months',
                'volume_of_production' => '30-50',
                'distance_of_planting_hills' => 250,
                'distance_of_planting_rows' => 250,
                'yield_per_hectare' => '30-50 tons',
            ],
            [
                'category_id' => 2,
                'name' => 'Banana',
                'crop_season' => 'all',
                'soil_type' => 'fertile loam',
                'time_of_planting' => 'All Season',
                'plant_population_per_hectare' => 1600,
                'maturity' => '12-15 months',
                'volume_of_production' => '20-40',
                'distance_of_planting_hills' => 250,
                'distance_of_planting_rows' => 250,
                'yield_per_hectare' => '20-40 tons',
            ],
        ];

        foreach ($crops as $crop) {
            Crop::create([
                'name' => $crop['name'],
                'category_id' => $crop['category_id'],
                'crop_season' => $crop['crop_season'],
                'soil_type' => $crop['soil_type'],
                'time_of_planting' => $crop['time_of_planting'],
                'plant_population_per_hectare' => $crop['plant_population_per_hectare'] ?? null,
                'maturity' => $crop['maturity'],
                'volume_of_production' => $crop['volume_of_production'] ?? null,
                'distance_of_planting_hills' => $crop['distance_of_planting_hills'] ?? null,
                'distance_of_planting_rows' => $crop['distance_of_planting_rows'] ?? null,
                'yield_per_hectare' => $crop['yield_per_hectare'],
            ]);
        }
    }
}
