<?php

namespace Database\Seeders;

use App\Models\Crop;
use Illuminate\Database\Seeder;

class CropSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $crops = [
            [
                'crop_name' => 'Abaca',
                'category' => 4,
                'planting_season_primary' => 'Start of rainy season (May-June)',
                'harvesting_period' => '16-24 months after planting (first harvest)',
                'growing_duration_days' => '480-720',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Amapalaya',
                'category' => 7,
                'planting_season_primary' => 'May-July, November-December',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Banana',
                'category' => 2,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => '8-12 months after planting',
                'growing_duration_days' => '240-360',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Bataw',
                'category' => 10,
                'planting_season_primary' => 'February-April, May-June',
                'harvesting_period' => '60-70 days after planting',
                'growing_duration_days' => '60-70',
                'ph_preference' => '6.0 - 7.5',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Bean',
                'category' => 10,
                'planting_season_primary' => 'May-June, November-January',
                'harvesting_period' => '60-90 days after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Not specified for Bean in general; please see specific types like Cowpea or Lima Bean.',
            ],
            [
                'crop_name' => 'Broccoli',
                'category' => 10,
                'planting_season_primary' => 'October-December',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '6.0 - 6.8',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Cabbage',
                'category' => 10,
                'planting_season_primary' => 'October-December, April-June',
                'harvesting_period' => '2-4 months after planting',
                'growing_duration_days' => '60-120',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Cacao',
                'category' => 4,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => 'Year round (after 3-5 years)',
                'growing_duration_days' => 'Perennial',
                'ph_preference' => '5.0 - 7.5',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Cantaloupe',
                'category' => 8,
                'planting_season_primary' => 'March-June, October-January',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 6.5',
                'soil_requirements' => 'Prefers loamy or alluvial soils that are rich in organic matter and well-drained.',
            ],
            [
                'crop_name' => 'Carrot',
                'category' => 6,
                'planting_season_primary' => 'March-September, October-December',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Cassava',
                'category' => 6,
                'planting_season_primary' => 'Start of rainy season (May-June), October-December',
                'harvesting_period' => '8-24 months after planting',
                'growing_duration_days' => '240-720',
                'ph_preference' => '5.5 - 6.5',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Cauliflower',
                'category' => 10,
                'planting_season_primary' => 'October-December, January-March',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Celery',
                'category' => 10,
                'planting_season_primary' => 'May-July, October-December',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Chayote',
                'category' => 7,
                'planting_season_primary' => 'February-March, May-June',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Chick Pea',
                'category' => 10,
                'planting_season_primary' => 'April-June, November-January',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '6.0 - 9.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Chinese Cabbage',
                'category' => 10,
                'planting_season_primary' => 'March-September',
                'harvesting_period' => '2 months after planting',
                'growing_duration_days' => '60',
                'ph_preference' => '6.0 - 7.5',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Citrus',
                'category' => 2,
                'planting_season_primary' => 'Year round (varies by type)',
                'harvesting_period' => 'Varies by type (6 months-2 years)',
                'growing_duration_days' => 'Varies',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Light sandy to medium-textured soils with good internal drainage. For oranges specifically, fine sandy loam or deep, loose, well-aerated soils free from stagnant water are ideal.',
            ],
            [
                'crop_name' => 'Coffee',
                'category' => 4,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => 'Year round (after establishment)',
                'growing_duration_days' => 'Perennial',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Thrives in deep, well-drained loam that is rich in nutrients, particularly potash, and has a good amount of humus. It grows best in rolling, sloping, well-drained lands of volcanic origin rich in organic matter.',
            ],
            [
                'crop_name' => 'Corn',
                'category' => 1,
                'planting_season_primary' => 'Dry season: October-December, Rainy: April-June',
                'harvesting_period' => '90-120 days after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Prefers deep, well-drained loam that is not too heavy. Alluvial and virgin soils produce good crops. Light sandy, gravely soils, and heavy clays are not ideal for healthy root development.',
            ],
            [
                'crop_name' => 'Cowpea',
                'category' => 10,
                'planting_season_primary' => 'January-March, May-June',
                'harvesting_period' => '60-90 days after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Can grow in soils ranging from sandy loam to heavy clay. For the best yields, a well-drained clay loam or silt loam soil is recommended.',
            ],
            [
                'crop_name' => 'Cucumber',
                'category' => 7,
                'planting_season_primary' => 'March-April, May-June',
                'harvesting_period' => '2 months after planting',
                'growing_duration_days' => '60',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Grows best in well-drained loamy or alluvial soils that are rich in organic matter, though it can also grow on heavy and light soils.',
            ],
            [
                'crop_name' => 'Eggplant',
                'category' => 7,
                'planting_season_primary' => 'January-April, May-June',
                'harvesting_period' => '2-5 months after planting',
                'growing_duration_days' => '60-150',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Requires fertile, well-drained sandy loam and clay loam soils. If the soil is not naturally fertile, it should be well-fertilized.',
            ],
            [
                'crop_name' => 'Garlic',
                'category' => 10,
                'planting_season_primary' => 'October-December, November-January',
                'harvesting_period' => '6-7 months after planting',
                'growing_duration_days' => '180-210',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'Needs fertile, well-drained loamy soils.',
            ],
            [
                'crop_name' => 'Ginger',
                'category' => 6,
                'planting_season_primary' => 'April-May (best time)',
                'harvesting_period' => '8-11 months after planting',
                'growing_duration_days' => '240-330',
                'ph_preference' => '5.0 - 7.0',
                'soil_requirements' => 'Prefers light but rich, loose soils with good drainage. Heavy soils can lead to reduced yields.',
            ],
            [
                'crop_name' => 'Kangkong',
                'category' => 10,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => '3-4 weeks after planting',
                'growing_duration_days' => '21-28',
                'ph_preference' => '6',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Lettuce',
                'category' => 10,
                'planting_season_primary' => 'March-June, April-May',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'Does well in sandy loam, clay loam, and silt loam soils that are well-supplied with organic matter. The soil should be well-drained but also able to retain moisture.',
            ],
            [
                'crop_name' => 'Mango',
                'category' => 2,
                'planting_season_primary' => 'November-February (flowering)',
                'harvesting_period' => 'March-June (120-135 days after flowering)',
                'growing_duration_days' => '120-135',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Grows best on rich, deep alluvial loams with good drainage. It can flourish on most soils as long as they are not too shallow.',
            ],
            [
                'crop_name' => 'Mungbean',
                'category' => 10,
                'planting_season_primary' => 'February-June',
                'harvesting_period' => '60-90 days after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.2 - 7.2',
                'soil_requirements' => 'Light to medium-textured soils with good aeration are best suited for this crop.',
            ],
            [
                'crop_name' => 'Muskmelon',
                'category' => 8,
                'planting_season_primary' => 'March-June, November-January',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 6.5',
                'soil_requirements' => 'Prefers loamy or alluvial soils that are rich in organic matter and well-drained.',
            ],
            [
                'crop_name' => 'Mustard',
                'category' => 10,
                'planting_season_primary' => 'January-March, May-July',
                'harvesting_period' => '1-2 months after planting',
                'growing_duration_days' => '30-60',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Thrives in sandy loam, silt loam, and clay loam soils that have a good supply of organic matter. The soil should be well-drained but also retentive of moisture.',
            ],
            [
                'crop_name' => 'Okra',
                'category' => 7,
                'planting_season_primary' => 'Year round, May-July',
                'harvesting_period' => 'Year round, 60-90 days',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 6.8',
                'soil_requirements' => 'Grows in fertile, well-drained sandy loam and clay loam soils.',
            ],
            [
                'crop_name' => 'Onion Bulb',
                'category' => 10,
                'planting_season_primary' => 'December-March, November-January',
                'harvesting_period' => '6-7 months after planting',
                'growing_duration_days' => '180-210',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'Requires fertile, well-drained sandy loam or alluvial soil.',
            ],
            [
                'crop_name' => 'Papaya',
                'category' => 2,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => '8-12 months after planting',
                'growing_duration_days' => '240-360',
                'ph_preference' => '6.5 - 7.0',
                'soil_requirements' => 'Does best on deep, well-drained soils. It cannot tolerate water-logging or soil compaction.',
            ],
            [
                'crop_name' => 'Patani',
                'category' => 10,
                'planting_season_primary' => 'May-June, November-December',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '5.4 - 5.6',
                'soil_requirements' => 'Grows from sandy loam to heavy clay, with well-drained clay loam or silt loam being best for heavy yields.',
            ],
            [
                'crop_name' => 'Patola',
                'category' => 7,
                'planting_season_primary' => 'March-September, May-July',
                'harvesting_period' => '60-90 days after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'Requires a well-drained loamy soil or an alluvial soil rich in organic matter.',
            ],
            [
                'crop_name' => 'Pea',
                'category' => 10,
                'planting_season_primary' => 'April-June, November-January',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'Grows well in fertile sandy soil or clay loam.',
            ],
            [
                'crop_name' => 'Peanut',
                'category' => 10,
                'planting_season_primary' => 'January-February, May-June',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Well-drained, aerated soils with adequate water-holding capacity, such as sandy loam, are very suitable.',
            ],
            [
                'crop_name' => 'Pechay',
                'category' => 10,
                'planting_season_primary' => 'January-March, May-June',
                'harvesting_period' => '1-2 months after planting',
                'growing_duration_days' => '30-60',
                'ph_preference' => '5.5 - 6.5',
                'soil_requirements' => 'Grows well in sandy loam, silt loam, and clay loam soils that are well-supplied with organic matter. The soil should be well-drained but also retain moisture.',
            ],
            [
                'crop_name' => 'Pepper',
                'category' => 7,
                'planting_season_primary' => 'February-March, May-June',
                'harvesting_period' => '2-5 months after planting',
                'growing_duration_days' => '60-150',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'For Sweet Pepper, well-drained light to medium textured soils are recommended. For Black Pepper, the soil should be well-drained, light to medium-textured, and rich in organic matter.',
            ],
            [
                'crop_name' => 'Pineapple',
                'category' => 4,
                'planting_season_primary' => 'April-June, August-November',
                'harvesting_period' => '18-24 months after planting',
                'growing_duration_days' => '540-720',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Prefers well-drained and aerated light to moderately heavy soil with a good amount of organic matter.',
            ],
            [
                'crop_name' => 'Potato',
                'category' => 6,
                'planting_season_primary' => 'February-March, October-December',
                'harvesting_period' => '3-4 months after planting',
                'growing_duration_days' => '90-120',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Does best in well-aerated sandy loams. A good crop can also be produced from deep, rich, well-drained, and friable clay, silt, or sandy loam.',
            ],
            [
                'crop_name' => 'Radish',
                'category' => 6,
                'planting_season_primary' => 'October-December',
                'harvesting_period' => '1-2 months after planting',
                'growing_duration_days' => '30-60',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Can grow in all types of soil, but a light, friable loam is best.',
            ],
            [
                'crop_name' => 'Rambutan',
                'category' => 2,
                'planting_season_primary' => 'Year round (varies by region)',
                'harvesting_period' => 'Varies by region',
                'growing_duration_days' => 'Perennial',
                'ph_preference' => '4.5 - 6.5',
                'soil_requirements' => 'Requires deep, not too heavy, well-drained soils that are rich in nutrients.',
            ],
            [
                'crop_name' => 'Rice',
                'category' => 5,
                'planting_season_primary' => 'Wet season: March-August, Dry: September-February',
                'harvesting_period' => '120-150 days after planting',
                'growing_duration_days' => '90-150',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Lowland Rice is best suited for heavy-textured soil with an impervious layer below the plow-sole. Upland Rice requires medium to heavy-textured soils with good water-holding capacity.',
            ],
            [
                'crop_name' => 'Rubber',
                'category' => 4,
                'planting_season_primary' => 'Year round (after establishment)',
                'harvesting_period' => '5-6 years after planting (tapping)',
                'growing_duration_days' => '1800+',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Thrives in permeable and well-aerated soils that allow roots good access to groundwater.',
            ],
            [
                'crop_name' => 'Sitao',
                'category' => 10,
                'planting_season_primary' => 'May-June, November-February',
                'harvesting_period' => '60-90 days after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.5 - 6.8',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Snap Bean',
                'category' => 10,
                'planting_season_primary' => 'May-June, October-December',
                'harvesting_period' => '2 months after planting',
                'growing_duration_days' => '60',
                'ph_preference' => '6.0 - 7.0',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Soybean',
                'category' => 10,
                'planting_season_primary' => 'January-March, May-June',
                'harvesting_period' => '60-90 days after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Deep, well-drained, fertile clay loam or sandy loam with high calcium content is ideal. Loam or sandy loam soils are best suited.',
            ],
            [
                'crop_name' => 'Squash',
                'category' => 7,
                'planting_season_primary' => 'May-June, October-December',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Requires well-drained loamy soils or alluvial soils rich in organic matter.',
            ],
            [
                'crop_name' => 'Sugarcane',
                'category' => 9,
                'planting_season_primary' => 'March-May (recommended), November',
                'harvesting_period' => '12-18 months after planting',
                'growing_duration_days' => '360-540',
                'ph_preference' => '5.5 - 7.0',
                'soil_requirements' => 'Prefers deep, permeable soils such as well-drained light sandy soil, alluvial soils, and volcanic soils.',
            ],
            [
                'crop_name' => 'Sweet Corn',
                'category' => 1,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.8 - 6.5',
                'soil_requirements' => 'Prefers deep, well-drained loam that is not too heavy. Alluvial and virgin soils produce good crops. Light sandy, gravely soils, and heavy clays are not ideal for healthy root development.',
            ],
            [
                'crop_name' => 'Sweet Pea',
                'category' => 10,
                'planting_season_primary' => 'February-March, April-June',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 7.5',
                'soil_requirements' => 'Grows well in fertile sandy soil or clay loam.',
            ],
            [
                'crop_name' => 'Sweet Potato',
                'category' => 6,
                'planting_season_primary' => 'Year round',
                'harvesting_period' => '6-12 months after planting',
                'growing_duration_days' => 'Perennial',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Taro',
                'category' => 6,
                'planting_season_primary' => 'Year round (varies by region)',
                'harvesting_period' => '7-12 months after planting',
                'growing_duration_days' => '210-360',
                'ph_preference' => '5.5 - 6.5',
                'soil_requirements' => 'Grows in fertile, sandy loam soil and requires a sufficient amount of water during its growing period.',
            ],
            [
                'crop_name' => 'Tomato',
                'category' => 7,
                'planting_season_primary' => 'January-April, May-June',
                'harvesting_period' => '2-5 months after planting',
                'growing_duration_days' => '60-150',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Silt loam, clay loam, and loam are ideal for large yields. Sand or sandy loam is preferred where the growing season is short and earliness is desired.',
            ],
            [
                'crop_name' => 'Upo',
                'category' => 7,
                'planting_season_primary' => 'November-March, April-May',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '6.0 - 6.7',
                'soil_requirements' => 'Thrives in well-drained loamy or alluvial soils rich in organic matter.',
            ],
            [
                'crop_name' => 'Watermelon',
                'category' => 8,
                'planting_season_primary' => 'January-March, April-May',
                'harvesting_period' => '2-3 months after planting',
                'growing_duration_days' => '60-90',
                'ph_preference' => '5.0 - 6.5',
                'soil_requirements' => 'Prefers well-drained loamy or alluvial soils rich in organic matter.',
            ],
            [
                'crop_name' => 'Yam',
                'category' => 6,
                'planting_season_primary' => 'August-September (varies by type)',
                'harvesting_period' => '6-12 months after planting',
                'growing_duration_days' => '180-360',
                'ph_preference' => '5.5 - 6.5',
                'soil_requirements' => 'Requires sandy soil with a loamy, permeable sub-soil.',
            ],
            [
                'crop_name' => 'Bountiful Beans',
                'category' => 10,
                'planting_season_primary' => 'May-June, October-December',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Cadius',
                'category' => 10,
                'planting_season_primary' => 'May-June, October-December',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Sigarilyas',
                'category' => 10,
                'planting_season_primary' => 'May-June, November-January',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Melon',
                'category' => 8,
                'planting_season_primary' => 'May-June, December-January',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Singkamas',
                'category' => 6,
                'planting_season_primary' => 'May-June',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Spinach',
                'category' => 10,
                'planting_season_primary' => 'April-May',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Talinum',
                'category' => 10,
                'planting_season_primary' => 'June-July, January-February',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Arrowroot',
                'category' => 6,
                'planting_season_primary' => 'May-June, November-December',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
            [
                'crop_name' => 'Beets',
                'category' => 6,
                'planting_season_primary' => 'June-July, November-December',
                'harvesting_period' => 'None',
                'growing_duration_days' => 'None',
                'ph_preference' => 'None',
                'soil_requirements' => 'None',
            ],
        ];

        foreach ($crops as $crop) {
            Crop::create([
                'name' => $crop['crop_name'],
                'category_id' => $crop['category'],
                'planting_season_primary' => $crop['planting_season_primary'],
                'harvesting_period' => $crop['harvesting_period'],
                'growing_duration_days' => $crop['growing_duration_days'],
                'ph_preference' => $crop['ph_preference'],
                'soil_requirement' => $crop['soil_requirements'],
            ]);
        }
    }
}
